### ISSUE TITLE
App refuses to run due to Battery Optimizations

### ISSUE THREAD

**Issue by 4mede** [atticuscornett/AtmosWeather#30]
**Describe the bug**
Even though I grant the app a battery optimizations exception, it thinks I haven't.
**To Reproduce**
Open the app, grant battery optimizations and see that it is not checked off on the list.
**Expected behavior**
Battery optimizations is checked.
**Screenshots**

**Version Info**
 - Platform: [e.g. web, Linux (deb x64), Android, etc.]
 - Atmos Version: [found in settings, e.g. 1.1.0]
Android, app version 2.2.0
**Additional context**

**Comment by atticuscornett** [comment]
Thanks for your interest in Atmos Weather! I have also observed this issue in a few cases. This shouldn't affect your ability to use the app or its performance as long as you grant the permission when prompted (just hit the "done" button to use the app - you may have to scroll down.) 

Since you brought this to my attention, I have moved it to my high-priority to-do list for Atmos Weather. I apologize if it takes me a long time to fix the bug, as I am currently busy with school and may not have time to address this promptly.

**Comment by 4mede** [comment]
Thank you. No rush on the fix. Yes, I saw the done button eventually, but initially thought I couldn't use the app.

**Comment by atticuscornett** [comment]
Well, I thought it might take a while to track down the bug but it turned out to be much simpler than I thought - it was just a typo (fixed in 19f511b.) In fixing this bug, I also found another bug that may have been why you thought the permission was required. The permission screen opened multiple times on the first app setup when it was only supposed to open once. (I must have forgotten to reinstall the app when testing the permissions update.) This has also been fixed. (e0ee742)

The bug fix will be out with the next update whenever it's ready, and I will let you know when it's released!

**Comment by 4mede** [comment]
Great, thank you!

**Comment by atticuscornett** [comment]
Thank you for your patience! The fix has been released with v2.2.1! (https://github.com/atticuscornett/AtmosWeather/releases/tag/v2.2.1)

**Comment by 4mede** [comment]
Thank you!
