### ISSUE TITLE
AppImage support

### ISSUE THREAD

**Issue by shuvashish76** [atticuscornett/AtmosWeather#8]
If possible, please make an AppImage available for linux users.

Unlike other packages [AppImage](https://github.com/AppImage/AppImageKit) is a community project & you could install without the need for a centralized store.
https://docs.appimage.org/packaging-guide/index.html

**Comment by atticuscornett** [comment]
Thanks for your interest in Atmos Weather! Earlier in development, an AppImage was provided for Linux but I stopped building to AppImage when I found that it could not run on startup (making it unable to provide notifications after computer restart without manually reopening.) I have since changed how the Linux startup code works so that issue may have been fixed. Regardless, I am happy to once again provide an AppImage for the 1.1.0 update when it releases. (It just may come with a note on what features do not work on the AppImage.)

**Comment by atticuscornett** [comment]
AppImages are now available in the latest release of Atmos Weather. (https://github.com/atticuscornett/AtmosWeather/releases/tag/v1.1.0)
As previously mentioned, the release includes a note of what is not supported in the AppImage version. Thanks for the suggestion!
