### ISSUE TITLE
Light Theme & Widgets

### ISSUE THREAD

**Issue by HonestAbe7** [atticuscornett/AtmosWeather#9]
Am I supposed to get weather notifications for each location I add since there is no way to have a default location?

I haven't yet tested this app fully to see if alerts happen with this app. 

Please consider a light theme for the app since I can't see the settings well using the dark theme. 

Also, please consider widgets for the current temperature or a notification. 

Thanks

**Comment by atticuscornett** [comment]
Thanks for checking out Atmos Weather! The app gives you notifications for all of the locations you have added. You can customize which notifications you receive for each location in settings. (At the moment there is no quick way to disable all notifications for any location, but this will be fixed in a future update.) The app does have a light mode designed, however, it currently uses whatever theme is your system default. I will plan to add a theme selector in settings in the future. Widgets are also already planned for a future update. For the moment, I have paused working on Atmos Weather as I have other projects that require more attention, so it may be a while before the next update comes out. (Additionally, the next update in progress migrates the project from Cordova to CapacitorJS, which requires a lot of work.) However, I will be sure to keep you updated on when your suggestions are added to the project. Thanks!

**Comment by atticuscornett** [comment]
@HonestAbe7 - Thanks again for your interest in the project. I am planning to work on Atmos Weather a bit more over the next month or so, and hopefully, I will get version 2.0 ready during that time. As previously mentioned, the big work for the update will be focused on migrating from Cordova to Capacitor, but I am also working on getting widgets working. Hopefully, I will also have time to add in-app theme selection. I will try to keep you updated as the features are added. Thank you for your patience, I know it's taken me a while to get back to work on this.

**Comment by atticuscornett** [comment]
I have a widget working now. Here's a peek at what it will look like:
![image](https://github.com/atticuscornett/AtmosWeather/assets/64325242/5dd9854f-5464-4400-a385-eba228784cc1)

The icons and text adapt to dark mode as well:
![image](https://github.com/atticuscornett/AtmosWeather/assets/64325242/f878176e-fb90-4ea0-bc73-9dde5bc2a689)

**Comment by atticuscornett** [comment]
Thank you for your patience. Atmos Weather v2.0.0 has now been released and adds a widget and a theme picker inside the app. You can download it from the [Atmos Weather website](https://atticuscornett.github.io/AtmosWeather/www/index.html). Thanks for the suggestions!

**Comment by Spark4000** [comment]
Widgets won't load for me. Location enabled, no battery optimization, background data enabled. Even rebooted device hoping that would solve issue.

**Comment by atticuscornett** [comment]
@Spark4000 - That's strange, I will spin up an emulator and see if I can track down the issue. By not loading, I assume you mean it is stuck just showing the blank dash place holders? You are in the US, correct?

**Comment by Spark4000** [comment]
Yes, no weather icon, and the Fahrenheit symbol is visible, but no temperature. Yes, I'm in the US

**Comment by atticuscornett** [comment]
I don't see anything wrong with widgets in Android 11. You say location enabled - does that include accessing the location in the background? Maybe you should try opening Atmos Weather, letting it run in the background for a few minutes, and then removing and re-adding the widget.

**Comment by atticuscornett** [comment]
I'm closing this issue because it's stale, and marking it as complete because the original suggestions have been implemented. You can open a new issue if you continue to have widget problems.
